version: '2'

services:
  mytranslatr.services.translationhistory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5101
      - ConnectionString=Server=sql.data;Database=MyTranslatr.Services.HistoryDb;User Id=sa;Password=Pass@word
    ports:
      - "5101:5101"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"